name: Test
on: push
env:
  TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
jobs:
  test:
    name: Test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        # Required with the hanging test workaround
        continue-on-error: true
        run: npm test
